title: Blog chulo
author: YoshiCrystal
description: joiojijoijiiojoi
theme: minima
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

menu:
  - title:             balls
    url:               /balls
  - title:             chinches
    url:               /chinches
